### ISSUE TITLE
Getting JS error using 'Add with credit' button

### ISSUE THREAD

**Issue by ddavis-palantir** [mdlutz24/drupal-meeting-parser#24]
When visiting app.slack.com and attempting to copy meeting nodes from Aug 1st 2024 some threads are resulting in an error and the button getting stuck on the '[Processing]' state.

In the console is a JS error:
`Uncaught TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at Object.parseText (scrape.js:80:25)
    at Object.<anonymous> (scrape.js:125:36)
    at NodeList.forEach (<anonymous>)
    at Object.parseThread (scrape.js:121:55)
    at Object.addThreadHeader (scrape.js:240:10)
    at Object.ensureScrollToTop (scrape.js:223:12)`

Here is a link to a thread from the Slack history which triggers this error:

`https://drupal.slack.com/archives/C226VLXBP/p1722520538009299`

**Comment by ddavis-palantir** [comment]
I modified the code in parseText and parseThread to allow for a case where parseText is getting called with a null argument.

`  parseText: function(textNode) {
    if (typeof textNode === 'undefined') {
      return;
    }
    [ ... ]`
    
 And over in parseThread I am checking the result of parseText() before proceeding to trim it.
 
 let parsedMessagePre = this.parseText(message.querySelector('.c-message_kit__gutter__right').childNodes[4])
 let parsedMessage = null;
 if (parsedMessagePre == null) {
    return; 
 } else {
    parsedMessage = parsedMessagePre.trim(); 
 }
